# Arithmetic Operations

In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4])
varadd = var +3
print(varadd)

[4 5 6 7]


In [11]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
# varadd = var1 + var2
varadd = np.add(var1,var2) 
print(varadd)

[ 6  8 10 12]


In [5]:
var = np.array([1,2,3,4])
varSub = var - 3
print(varSub)

[-2 -1  0  1]


In [7]:
var = np.array([1,2,3,4])
varMulti = var * 3
print(varMulti)

[ 3  6  9 12]


In [8]:
var = np.array([1,2,3,4])
varDiv = var / 3
print(varDiv)

[0.33333333 0.66666667 1.         1.33333333]


In [9]:
var = np.array([1,2,3,4])
varMod = var % 3
print(varMod)

[1 2 0 1]


## 2D array

In [14]:
var1 = np.array([[1,2,3,4],[5,6,7,8]])
var2 = np.array([[2,3,4,5],[6,7,8,9]])
varadd = np.add(var1, var2)
print(varadd)

[[ 3  5  7  9]
 [11 13 15 17]]


In [18]:
var1 = np.array([[1,2,3,4],[5,6,7,8]])
var2 = np.array([[2,3,4,5],[6,7,8,9]])
varMul = np.multiply(var1, var2)
print(varMul)

[[ 2  6 12 20]
 [30 42 56 72]]
