In [1]:
import numpy as np

In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
print(var1 + var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [4]:
var1 = np.array([1,2,3])
var2 = np.array([[1],[2],[3]])
print(var1.shape)
print()
print(var1)
print()

print(var2.shape)
print()
print(var2)
print()

print(var1 + var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [7]:
x = np.array([[1],[2]])
y = np.array([[1,2,3],[1,2,3]])
print(x.shape)
print(y.shape)
print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]
