In [1]:
import numpy as np

In [5]:
var = np.array([1,2,3,4])
co = var.copy()

print(var)
print(co)
print()

var[0] = 2
print(var)
print(co)
print()

[1 2 3 4]
[1 2 3 4]

[2 2 3 4]
[1 2 3 4]



In [6]:
var1 = np.array([1,2,3,4])
vw = var1.view()

print(var1)
print(vw)
print()

var1[0] = 2
print(var1)
print(vw)
print()

[1 2 3 4]
[1 2 3 4]

[2 2 3 4]
[2 2 3 4]

