## Demo

In [2]:
import numpy as np
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [5]:
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


## Compare time list vs numpy

In [8]:
%timeit [i**4 for i in range(1,9)]

2.57 µs ± 259 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
%timeit np.arange(1,9)**4

2.33 µs ± 263 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Create numpy

In [10]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
print(y)

[1 2 3 4]


In [11]:
y = np.array([1,2,3,4])
print(y)

[1 2 3 4]


In [13]:
print(y.ndim)

1


In [12]:
l = []
for i in range(5):
    inpt = input("Enter: ")
    l.append(inpt)
print(l)

Enter: 2
Enter: 3
Enter: 1
Enter: 4
Enter: 6
['2', '3', '1', '4', '6']


In [14]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [2 3 4 5]]
2


In [15]:
# must declare same element in array
ar2 = np.array([[1,2,3,4],[2,3,4]])
print(ar2)
print(ar2.ndim)

[list([1, 2, 3, 4]) list([2, 3, 4])]
1


C:\Users\01154\AppData\Local\Temp\ipykernel_7524\327119849.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2 = np.array([[1,2,3,4],[2,3,4]])


In [18]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [20]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Create numby by function

1. <strong>Zeros</strong>

In [21]:
import numpy as np
ar_zero = np.zeros(4) # 4 element in array
print(ar_zero)

[0. 0. 0. 0.]


In [22]:
ar_zero1 = np.zeros((3,4)) # 3 parent, with 4 element child in 1 parent
print(ar_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2. <strong>Ones</strong>

In [24]:
import numpy as np
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


3. <strong>Empty</strong>

In [25]:
import numpy as np
ar_emp = np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


4. <strong>Range</strong>

In [26]:
import numpy as np
ar_range = np.arange(4)
print(ar_range)

[0 1 2 3]


5. <strong>Diagonal</strong>

In [27]:
import numpy as np
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


6. <strong>linspace</strong>

In [34]:
import numpy as np
ar_lins = np.linspace(0,10,num=5)
print(ar_lins)

[ 0.   2.5  5.   7.5 10. ]


## Create numpy with random

1. <strong>Rand()</strong>

In [35]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.25419659 0.54984877 0.27957609 0.99728709]


In [36]:
var1 = np.random.rand(2,5)
print(var1)

[[0.35778994 0.18663043 0.60852859 0.82074885 0.86952068]
 [0.2061702  0.20533135 0.46082707 0.05211354 0.51601059]]


2. <strong>randn()</strong>

In [37]:
var = np.random.randn(5)
print(var)

[ 0.20152389 -0.15835304 -1.12848554 -0.49460012 -1.53310349]


3. <strong>ranf()</strong>

In [38]:
var = np.random.ranf(4)
print(var)

[0.23043823 0.46141427 0.26035653 0.80387629]


4. <strong>randint()</strong>

In [39]:
# np.random.randint(min, max, total_value)
var = np.random.randint(5,20,5)
print(var)

[12  6  6  8  5]


# Data type

In [40]:
import numpy as np
var = np.array([1,2,3,4,11,12,13,14,15])
print("Data type: ",var.dtype)

Data type:  int32


In [41]:
var = np.array([1.0,2.4,4.5,6.3])
print("Data type: ",var.dtype)

Data type:  float64


In [42]:
var = np.array(["A","C","D","T"])
print("Data type: ",var.dtype)

Data type:  <U1


In [43]:
var = np.array(["A","C","D","T",1,2,3,4])
print("Data type: ",var.dtype)

Data type:  <U11


In [44]:
var = np.array([1,2,3,4,11,12,13,14,15],dtype=np.int8)
print("Data type: ",var.dtype)

Data type:  int8


In [45]:
var = np.array([1,2,3,4,11,12,13,14,15],dtype="f")
print("Data type: ",var.dtype)

Data type:  float32


In [47]:
var = np.array([1,2,3,4,11,12,13,14,15])
new = np.float32(var)
print("Data type: ",var.dtype)
print("Data type: ",new.dtype)
print(var)
print(new)

Data type:  int32
Data type:  float32
[ 1  2  3  4 11 12 13 14 15]
[ 1.  2.  3.  4. 11. 12. 13. 14. 15.]


In [48]:
var = np.array([1,2,3,4,11,12,13,14,15])
new = np.float32(var)
new2 = np.int_(new)
print("Data type: ",var.dtype)
print("Data type: ",new.dtype)
print("Data type: ",new2.dtype)
print(var)
print(new)
print(new2)

Data type:  int32
Data type:  float32
Data type:  int32
[ 1  2  3  4 11 12 13 14 15]
[ 1.  2.  3.  4. 11. 12. 13. 14. 15.]
[ 1  2  3  4 11 12 13 14 15]


In [49]:
x =  np.array([1,2,3,4,11,12,13,14,15])
new = x.astype(float)
print(x)
print(new)

[ 1  2  3  4 11 12 13 14 15]
[ 1.  2.  3.  4. 11. 12. 13. 14. 15.]
