In [1]:
import numpy as np

# Indexing

In [5]:
var = np.array([9,8,7,6])
#               0 1 2 3
#               4-3-2-1
print(var[1])
print(var[-1])

8
6


In [9]:
var = np.array([[9,8,7],[6,5,4]])
print(var)
print(var.ndim)
print()

print(var[0,1])

[[9 8 7]
 [6 5 4]]
2

8


In [13]:
var = np.array([[[9,8,7],[6,5,4],[3,2,1]]])
print(var)
print(var.ndim)
print()
print(var[0,1,2])
print(var[0,0,1])

[[[9 8 7]
  [6 5 4]
  [3 2 1]]]
3

4
8


# Slicing
 - With 1D: x[start:stop:step]

In [20]:
var = np.array([1,2,3,4,5,6,7])
print(var)
print()

print("print arr from index 2 to below 5:", var[2:5])
print("print arr from index 2 to end", var[2:])
print("print arr from start to below index 5", var[:5])
print("print arr with start 2, stop 5, step 2", var[2:5:2])

[1 2 3 4 5 6 7]

print arr from index 2 to below 5: [3 4 5]
print arr from index 2 to end [3 4 5 6 7]
print arr from start to below index 5 [1 2 3 4 5]
print arr with start 2, stop 5, step 2 [3 5]


- With 2D: x[index_array_child, start:stop:step]

In [22]:
var = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(var)
print()
print(var[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[7 8 9]
