# insert

In [1]:
import numpy as np

In [9]:
var = np.array([1,2,3,4])
print(var)
x = np.insert(var,2,40) # insert 40 at index 2 
print(x)
y = np.insert(var,(2,4),40) # insert 40 at index 2 and 4
print(y)
z = np.append(var, 5)
print(z)

[1 2 3 4]
[ 1  2 40  3  4]
[ 1  2 40  3  4 40]
[1 2 3 4 5]


In [5]:
var = np.array([[1,2,3],[4,5,6]])
x = np.insert(var,2,6, axis =0)# insert 6 at index 2, axis = 0 is same level element
print(x)

[[1 2 3]
 [4 5 6]
 [6 6 6]]


In [6]:
var = np.array([[1,2,3],[4,5,6]])
x = np.insert(var,2,6, axis =1)# insert 6 at index 2 , axis = 1 is child element
print(x)

[[1 2 6 3]
 [4 5 6 6]]


In [7]:
var = np.array([[1,2,3],[4,5,6]])
x = np.insert(var,2,[22,23], axis =1)# insert 22,23 at index 2 , axis = 1 is child element
print(x)

[[ 1  2 22  3]
 [ 4  5 23  6]]


In [8]:
var = np.array([[1,2,3],[4,5,6]])
x = np.insert(var,2,[22,23,24], axis =0)# insert 22,23,24 at index 2 
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [22 23 24]]


# Delete

In [10]:
var_del = np.array([1,2,3,4])
print(var_del)
d = np.delete(var_del,2) #delete element with index 2
print(d)

[1 2 3 4]
[1 2 4]
