In [1]:
import numpy as np

In [2]:
var  = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [4]:
var1  = np.array([[9,8,7,6,5],[4,3,2,1,0]])
print(var1)

for i in var1:
    for j in i:
        print(j)

[[9 8 7 6 5]
 [4 3 2 1 0]]
9
8
7
6
5
4
3
2
1
0


In [6]:
var2  = np.array([[[9,8,7],[6,5,4],[3,2,1]]])
print(var2)

for i in var2:
    for j in i:
        for k in j:
            print(k)

[[[9 8 7]
  [6 5 4]
  [3 2 1]]]
9
8
7
6
5
4
3
2
1


In [9]:
var3  = np.array([[[9,8,7],[6,5,4],[3,2,1]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3, flags=["buffered"], op_dtypes=["S"]):
    print(i)

[[[9 8 7]
  [6 5 4]
  [3 2 1]]]
3

b'9'
b'8'
b'7'
b'6'
b'5'
b'4'
b'3'
b'2'
b'1'


In [10]:
var3  = np.array([[[9,8,7],[6,5,4],[3,2,1]]])
print(var3)
print(var3.ndim)
print()

for i in np.ndenumerate(var3):
    print(i)

[[[9 8 7]
  [6 5 4]
  [3 2 1]]]
3

((0, 0, 0), 9)
((0, 0, 1), 8)
((0, 0, 2), 7)
((0, 1, 0), 6)
((0, 1, 1), 5)
((0, 1, 2), 4)
((0, 2, 0), 3)
((0, 2, 1), 2)
((0, 2, 2), 1)
