# Join Array

In [1]:
import numpy as np

In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
ar = np.concatenate((var1, var2))
print(ar)

[1 2 3 4 5 6 7 8]


In [5]:
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[5,6],[7,8]])
ar1 = np.concatenate((x1, x2))
print(ar1)
print()
ar1 = np.concatenate((x1, x2), axis=1)
print(ar1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])
ar_1 = np.stack((var_1, var_2))
print(ar_1)
print()
ar_1 = np.stack((var_1, var_2),axis=1)
print(ar_1)
print()
ar_1 = np.hstack((var_1, var_2)) #row
print(ar_1)
print()
ar_1 = np.vstack((var_1, var_2)) #column
print(ar_1)
print()
ar_1 = np.dstack((var_1, var_2)) # height
print(ar_1)

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# Split Array

In [12]:
var = np.array([1,2,3,4,5,6])
print(var)
ar = np.array_split(var,4)
print(ar)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [14]:
var1 = np.array([[1,2],[3,4],[5,6]])
print(var1)
ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3, axis=1)
print(ar1)
print(ar2)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
