# Shape

In [1]:
import numpy as np

In [4]:
var = np.array([[1,2],[3,4]])
print(var)
print("Shape: ",var.shape)

[[1 2]
 [3 4]]
Shape:  (2, 2)


In [8]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)
print("Shape: ",var1.shape)
print("dim: ", var1.ndim)

[[[[1 2 3 4]]]]
Shape:  (1, 1, 1, 4)
dim:  4


# Reshape

In [13]:
var = np.array([1,2,3,4,5,6])
x = var.reshape(2,3) # 3 element child in 1 parent * 2
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
2


In [12]:
x = var.reshape(3,2) # 2 element child in 1 parent * 3
print(x)
print(x.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [14]:
var = np.array([1,2,3,4,5,6,7,8,9])
x = var.reshape(3,3) # 3 element child in 1 parent * 3
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [16]:
var = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9])
x = var.reshape(2,3,3) # (3 element child in 1 parent * 3) * 2
print(x)
print(x.ndim) #3d dimemsion

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [17]:
var = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9])
x = var.reshape(2,3,3) # (3 element child in 1 parent * 3) * 2
print(x)
print(x.ndim)
print()
x1 = x.reshape(-1)
print(x1)
print(x1.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
1
