# Matrix

In [1]:
import numpy as np

In [11]:
var = np.matrix([[1,2,3],[4,5,6]]) # dim (2,3)
var1 = np.matrix([[1,2,3],[4,5,6]])
print(var)
print(type(var))
print()
print(var + var1)
print()
print(var - var1)
print()
# print(var * var1)  #can not multiply with not same dimension 
print()
print(var / var1)

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>

[[ 2  4  6]
 [ 8 10 12]]

[[0 0 0]
 [0 0 0]]


[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
var = np.matrix([[1,2],[3,4]]) 
var1 = np.matrix([[1,2],[3,4]])
print(var * var1)
print()
print(var.dot(var1))

[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]


In [15]:
var = np.array([[1,2,3],[4,5,6]])
print(var)
print(type(var))
print()
print(var*var)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

[[ 1  4  9]
 [16 25 36]]


# Matrix Function
1. <strong>Transpose</strong>
2. <strong>Swapaxes</strong>
3. <strong>Inverse</strong>
4. <strong>Power</strong>
5. <strong>Determinate</strong>

1. <strong>Transpose</strong>

In [1]:
import numpy as np

In [4]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


2. <strong>Swapaxes</strong>

In [6]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [7]:
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.swapaxes(var,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


3. <strong>Inverse</strong>

In [8]:
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.inv(var))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


4. <strong>Power</strong>

In [11]:
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.matrix_power(var,2))
print()
print(np.linalg.matrix_power(var,0))
print()
print(np.linalg.matrix_power(var,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


5. <strong>Determinate</strong>

In [12]:
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.det(var))

[[1 2]
 [3 4]]

-2.0000000000000004


In [13]:
var = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var)
print()
print(np.linalg.det(var))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
